/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:55a11365-f19c-4296-b418-57c59bd6836c",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_gKuKzBIjY",
    "aws_user_pools_web_client_id": "6ikk07b5p64h2073jtjljduobo",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "contactstorage210955-dev",
    "aws_user_files_s3_bucket_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://ux2d4aa4ejemtg24emt7esizpe.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fux6n35gwfffhnkyymoaq3eubi"
};


export default awsmobile;
